#!/usr/bin/env python3
from glob import glob
from itertools import chain
from os.path import commonpath, dirname, isdir, realpath
from subprocess import run as srun
from sys import argv, exit
from uuid import uuid4

mnts = [] # Mounts
cargs = [] # Container execution args
args = argv[1:] # User args
if len(args) > 0:
    paths = []
    for arg in reversed(args):
        if arg.startswith("-"):
            break

        paths += [realpath(arg)]

    commondir = commonpath(paths) if paths else ""
    for path in paths:
        frompath = realpath(path)

        mntpath = "/mnt/" + path[len(commondir)+1:] if len(commondir) > 0 else path
        topath = mntpath

        if isdir(path):
            frompath += "/"
            topath += "/"

        mnts += [f"-v '{frompath}':'{topath}':rw"]

    if "--init" in args:
        cargs += ["-it"]

image = "docker.io/akiraheid/eslint:latest"
cmd = " ".join([
        "##TOOL##", "run", "--name", f"eslint-{uuid4()}", "--network", "none",
        "--rm"
        ] + cargs + mnts + [image] + args)

try:
    srun(cmd, shell=True, check=True)
except CalledProcessError:
    # Errors are thrown when issues are found. Ignore
    pass
finally:
    srun(["##TOOL##", "pull", image], shell=True, capture_output=True)
