#!/bin/bash

if [ $# == 0 ]; then
	echo "No application specified to install. Exiting."
	exit 0
fi

tools=(docker podman)
for _tool in "${tools[@]}"; do
	toolpath=$(which "$_tool")
	if [ -n "$toolpath" ]; then
		tool=$_tool
		break
	fi
done

echo "Container runtime tool is $tool"

if [ -z "$BIN_PATH" ]; then
	BIN_PATH=~/.local/bin
	echo "BIN_PATH not defined. Using default $BIN_PATH"
fi

if [ -z "$APP_DESKTOP_PATH" ]; then
	APP_DESKTOP_PATH=~/.local/share/applications
	echo "APP_DESKTOP_PATH not defined. Using default $APP_DESKTOP_PATH"
fi

if [ -z "$(which xclip)" ]; then
	echo "xclip is required for one- and two-way clipboard functionality."
	echo "You don't have to install it, but you won't be able to copy/paste into"
	echo "and out of applications."
	sudo apt install xclip
fi

apps=("$@")
for app in "${apps[@]}"; do
	# Remove possible trailing forward slash from autocomplete
	app=$(basename "$app")

	echo "Installing $app..."
	pushd "$app" > /dev/null

	apppath=$BIN_PATH/$app
	cp -v "./$app" "$apppath"
	sed -i "s/##TOOL##/$tool/" "$apppath"
	chmod 750 "$apppath"

	desktop=./$app.desktop
	if [ -f "$desktop" ]; then
		cp -v "$desktop" "$APP_DESKTOP_PATH"/
		echo "You can now see this application in the application menu."
	else
		echo "No desktop file. The application won't show up in the application menu."
	fi

	popd > /dev/null
	echo "Installing $app... done"
done
