#!/bin/bash

set -e

if [ $# == 0 ]; then
	echo "No application specified to install. Exiting."
	exit 0
fi

tools=(docker podman)
for _tool in ${tools[@]}; do
	toolpath=`which $_tool`
	if [ -n "$toolpath" ]; then
		tool=$_tool
		break
	fi
done

echo "Container runtime tool is $tool"

if [ -z "$BIN_PATH" ]; then
	BIN_PATH=~/.local/bin/
	echo "BIN_PATH not defined. Using default $BIN_PATH"
fi

if [ -z "$APP_DESKTOP_PATH" ]; then
	APP_DESKTOP_PATH=~/.local/share/applications
	echo "APP_DESKTOP_PATH not defined. Using default $APP_DESKTOP_PATH"
fi

apps=($@)
for app in ${apps[@]}; do
	echo "Installing $app..."
	pushd $app > /dev/null
	apppath=$BIN_PATH/$app
	cp ./$app $apppath
	sed -i "s/##TOOL##/$tool/" $apppath
	chmod 750 $apppath

	desktop=./$app.desktop
	if [ -f "$desktop" ]; then
		cp "$desktop" "$APP_DESKTOP_PATH"
		popd > /dev/null
		echo "Installing $app... done"
	fi
done
