#!/bin/bash

backend=${CONTAINER_BACKEND:-podman}

app=clamav
image=docker.io/akiraheid/${app}:latest

happdir=$HOME/Documents/${app}
hdatadir=${happdir}/data
hdbdir=${happdir}/db

cdatadir=/home/${app}/${app}
cdbdir=/var/lib/${app}

mkdir -p "$hdatadir" "$hdbdir"

hargs=("--network" "none" "--rm")
hargs+=("--volume" "${hdatadir}/:${cdatadir}/:rw")
hargs+=("--volume" "${hdbdir}/:${cdbdir}/:rw")
hargs+=("--name" "${app}-$(cat /proc/sys/kernel/random/uuid)")

cargs=()
for token in "${@}"; do
	if [ -f "$token" ]; then
		hpath=$(readlink -f "${token}")

		# Remove leading slash
		noleading=$(echo "${hpath}" | cut -c2-)
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}:${cpath}:ro")
		cargs+=("${cpath}")
	elif [ -d "$token" ]; then
		hpath=$(readlink -f "${token}")

		# Remove leading slash
		noleading=$(echo "${hpath}" | cut -c2-)
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}/:${cpath}/:ro")
		cargs+=("${cpath}")
	else
		cargs+=("${token}")
	fi
done

dbargs=("--name" "clamav-db-update" "--rm")
dbargs+=("--volume" "${hdbdir}/:${cdbdir}/:rw")
"$backend" run "${dbargs[@]}" "$image" freshclam

# Run scan without network access to stay private
"$backend" run "${hargs[@]}" "$image" clamscan "${cargs[@]}"

# Pull new images in the background and don't print anything to the terminal
"$backend" pull "$image" >/dev/null 2>&1 &
