#!/bin/bash

image=docker.io/akiraheid/clamav:latest

hdatadir=$HOME/Documents/clamav/data
hdbdir=$HOME/Documents/clamav/db

cdatadir=/home/clamav/clamav
cdbdir=/var/lib/clamav

mkdir -p "$hdatadir" "$hdbdir"

hargs=("--network" "none" "--rm")
hargs+=("--volume" "${hdatadir}/:${cdatadir}/:rw")
hargs+=("--volume" "${hdbdir}/:${cdbdir}/:rw")
hargs+=("--name" "${app}-$(cat /proc/sys/kernel/random/uuid)")

cargs=()

for token in "${@}"; do

	if [ -f "$token" ]; then
		hpath=`readlink -f "${token}"`

		# Remove leading slash
		noleading=`echo "${hpath}" | cut -c2-`
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}:${cpath}:ro")
		cargs+=("${cpath}")
	elif [ -d "$token" ]; then
		hpath=`readlink -f "${token}"`

		# Remove leading slash
		noleading=`echo "${hpath}" | cut -c2-`
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}/:${cpath}/:ro")
		cargs+=("${cpath}")
	else
		cargs+=("${token}")
	fi
done

echo "Updating database..."
dbargs=("--name" "clamav-db-update" "--rm")
dbargs+=("--volume" "${hdbdir}/:${cdbdir}/:rw")
##TOOL## run "${dbargs[@]}" $image freshclam

# Run scan without network access to stay private
echo "Scanning..."
##TOOL## run "${hargs[@]}" $image clamscan "${cargs[@]}"

##TOOL## pull $image
