#!/bin/bash
set -e

# image is used in a line that is parsed as a comment becaue of leading '##' in
# '##TOOL##'. When this file is installed on a system, the '##TOOL##' is
# replaced with the system's container execution tool.
# shellcheck disable=SC2034
image=docker.io/akiraheid/pylint:latest

cdatadir=/root

# Arguments for the run command
hargs=("--name" "pylint-$(uuidgen)" "--network" "none" "--rm")

# Arguments for the container entrypoint
cargs=()

# pylint search order specified in the documentation
# https://pylint.readthedocs.io/en/v3.1.0/user_guide/usage/run.html#command-line-options
# Ignoring paths that search parent paths.
pylintrcPaths=(./pylintrc ./pylintrc.toml ./.pylintrc ./.pylintrc.toml)
pylintrcPaths+=(./pyproject.toml ./setup.cfg ./tox.ini "${PYLINTRC:-/fakefile}")
pylintrcPaths+=("$HOME/.pylintrc" "$HOME/.config/pylintrc" "/etc/pylintrc")

echo "Finding pylint configuration..."
cpath=/etc/pylintrc
for i in "${pylintrcPaths[@]}"; do
	abspath=$(readlink -f "$i")
	if [ -f "$abspath" ]; then
		hargs+=("--volume" "${abspath}:${cpath}:ro")
		break
	fi
done

for token in "${@}"; do
	if [ -f "$token" ]; then
		hpath=$(readlink -f "${token}")

		# Remove leading slash
		noleading=$(echo "${hpath}" | cut -c2-)
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}:${cpath}:rw")
		cargs+=("${cpath}")
	elif [ -d "$token" ]; then
		hpath=$(readlink -f "${token}")

		# Remove leading slash
		noleading=$(echo "${hpath}" | cut -c2-)
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}/:${cpath}/:rw")
		cargs+=("${cpath}")
	else
		cargs+=("${token}")
	fi
done

##TOOL## run "${hargs[@]}" $image "${cargs[@]}"

##TOOL## pull $image
