#!/bin/bash

HOST_DIR=$HOME/Documents/openoffice
CONTAINER_DIR=/root

if [ $# == 1 ]; then
	ARG=$CONTAINER_DIR/$(basename "$1")

	fullpath=$(readlink -f "$1")
	if [[ "$fullpath" != $HOST_DIR* ]]; then
		ARG=/tmp/$(basename "$1")
		MOUNT_FILE=
	fi
fi

mkdir -p $HOST_DIR

IMAGE=docker.io/akiraheid/openoffice:latest

##TOOL## run \
	-d \
	-e DISPLAY=unix${DISPLAY} \
	--name "OpenOffice-$(cat /proc/sys/kernel/random/uuid)" \
	--network none \
	--rm \
	-v $HOST_DIR/:$CONTAINER_DIR/:rw \
	-v openoffice-config:/root/.openoffice/:rw \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v /usr/share/X11/xkb/:/usr/share/X11/xkb/:ro \
	${MOUNT_FILE+-v "$fullpath":"$ARG":rw} \
	$IMAGE ${ARG+"$ARG"}

##TOOL## pull $IMAGE
