#!/bin/bash
image=docker.io/aquasec/trivy:latest

happdir=$HOME/Documents/trivy
hcachedir=${happdir}/cache
hdatadir=${happdir}/data

ccachedir=/root/.cache
cdatadir=/root/data

mkdir -p "$hcachedir" "$hdatadir"

hargs=("--name" "${app}-$(cat /proc/sys/kernel/random/uuid)")
hargs+=("--volume" "${hcachedir}/:${ccachedir}/:rw")
hargs+=("--rm")

cargs=()

for token in "${@}"; do
	cpath=${cdatadir}/${token}

	if [ -f "$token" ]; then
		hpath=$(readlink -f "${token}")
		hargs+=("--volume" "${hpath}:${cpath}:ro")
		cargs+=("${cpath}")
	elif [ -d "$token" ]; then
		hpath=$(readlink -f "${token}")
		hargs+=("--volume" "${hpath}/:${cpath}/:ro")
		cargs+=("${cpath}")
	else
		cargs+=("${token}")
	fi
done

##TOOL## run "${hargs[@]}" "${image}" "${cargs[@]}"

##TOOL## pull "${image}"
