#!/bin/bash

backend=${CONTAINER_BACKEND:-podman}

app=shellcheck
image=docker.io/akiraheid/${app}:latest

# Host directories
hdatadir=$HOME/Documents/${app}

# Container directories
cdatadir=/app

mkdir -p "$hdatadir"

hargs=("--name" "${app}-$(cat /proc/sys/kernel/random/uuid)")
hargs+=("--network" "none" "--rm")
hargs+=("--volume" "${hdatadir}/:${cdatadir}/:rw")
cargs=()

for token in "${@}"; do
	if [ -f "$token" ]; then
		hpath=$(readlink -f "${token}")

		# Remove leading slash
		noleading=$(echo "${hpath}" | cut -c2-)
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}:${cpath}:ro")
		cargs+=("${cpath}")
	elif [ -d "$token" ]; then
		hpath=$(readlink -f "${token}")

		# Remove leading slash
		noleading=$(echo "${hpath}" | cut -c2-)
		cpath=${cdatadir}/${noleading}

		hargs+=("--volume" "${hpath}/:${cpath}/:ro")
		cargs+=("${cpath}")
	else
		cargs+=("${token}")
	fi
done

"$backend" run "${hargs[@]}" $image "${cargs[@]}"

"$backend" pull $image
