#!/bin/bash

backend=${CONTAINER_BACKEND:-podman}

app=deluge
image=docker.io/akiraheid/${app}:2.2.0

hconfigdir=${XDG_CONFIG_HOME:-$HOME/.config/${app}}
hdatadir=${DELUGE_DATA_DIR:-$HOME/Downloads/${app}}
hsharedir=${XDG_DATA_HOME:-$HOME/.local/share/$app}

cconfigdir=$HOME/.config
cdatadir=$HOME/Downloads
csharedir=$HOME/.local/share

mkdir -pv "$hconfigdir" "$hdatadir" "$hsharedir"

# Arguments for x11docker
opts=("--backend=${backend}" "--clipboard=superv" "--network")
opts+=("--name" "${app}-$(cat /proc/sys/kernel/random/uuid)")

# Arguments to pass through x11docker to run command
#xdargs=("--" "-p" "61619:58008" "-p" "54237-54337:42069-42169")
xdargs=("--" "--volume" "${hconfigdir}/:${cconfigdir}/:rw")
xdargs+=("--volume" "${hdatadir}/:${cdatadir}/:rw")
xdargs+=("--volume" "${hsharedir}/:${csharedir}/:rw")

# Arguments for the application
cargs=()

for token in "${@}"; do
	if [ -f "$token" ]; then
		hpath=$(readlink -f "${token}")
		xdargs+=("--volume" "${hpath}:${hpath}:rw")
		cargs+=("${hpath}")
	elif [ -d "$token" ]; then
		hpath=$(readlink -f "${token}")
		xdargs+=("--volume" "${hpath}/:${hpath}/:rw")
		cargs+=("${hpath}")
	else
		cargs+=("${token}")
	fi
done

x11docker "${opts[@]}" "${xdargs[@]}" -- "$image" "${cargs[@]}"

"$backend" pull "$image"
