#!/bin/bash

_app=keepassxc
_host_datadir=${KEEPASSXC_DATA_DIR:-$HOME/Documents/$_app}
_container_datadir=$HOME

image=docker.io/akiraheid/keepassxc:latest

mkdir -pv "$_host_datadir"

# Arguments for x11docker
opts="--desktop --backend=##TOOL## --clipboard=oneway"

# Arguments to pass through x11docker to run command
xdargs="-- --volume ${_host_datadir}:${_container_datadir}:rw"

# Mount user-specified file, if given
_file=${1:-}
if [ -n "${_file}" ]; then
	if [ -f "${_file}" ]; then
		_file=`readlink -f "${_file}"`
		_base=`basename ${_file}`
		xdargs="$xdargs --volume ${_file}:/${_base}:rw"
	fi
fi

x11docker $opts $xdargs -- $image $args >/dev/null 2>&1 &

##TOOL## pull $image
