#!/bin/bash

HOST_DIR=~/Documents/keepassxc
CONTAINER_DIR=/root/data

mkdir -p $HOST_DIR

if [ $# == 1 ]; then
	ARG=$CONTAINER_DIR/$(basename "$1")
	fullpath=$(readlink -f "$1")
	if [[ "$fullpath" != $HOST_DIR* ]]; then
		ARG=/tmp/$(basename "$1")
		MOUNT_FILE=
	fi
fi

IMAGE=docker.io/akiraheid/keepassxc:latest

##TOOL## run \
	-d \
	-e DISPLAY=unix${DISPLAY} \
	--name keepassxc-$(uuidgen) \
	--network none \
	--rm \
	-v keepassxc-config:/root/.config/keepassxc/:rw \
	-v $HOST_DIR/:$CONTAINER_DIR/:rw \
	-v /tmp/.X11-unix:/tmp/.X11-unix:rw \
	-v /usr/share/X11/xkb/:/usr/share/X11/xkb/:ro \
	${MOUNT_FILE+-v "$fullpath":"$ARG":rw} \
	$IMAGE ${ARG+"${ARG}"}

##TOOL## pull $IMAGE
